[2024-09-30T14:33:01.190+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-30T14:33:01.204+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tab_soccer_statics.fact_matches_statistics manual__2024-09-30T14:31:47.119862+00:00 [queued]>
[2024-09-30T14:33:01.211+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tab_soccer_statics.fact_matches_statistics manual__2024-09-30T14:31:47.119862+00:00 [queued]>
[2024-09-30T14:33:01.211+0000] {taskinstance.py:2865} INFO - Starting attempt 4 of 4
[2024-09-30T14:33:01.224+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): fact_matches_statistics> on 2024-09-30 14:31:47.119862+00:00
[2024-09-30T14:33:01.233+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4332) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-30T14:33:01.234+0000] {standard_task_runner.py:72} INFO - Started process 4345 to run task
[2024-09-30T14:33:01.234+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tab_soccer_statics', 'fact_matches_statistics', 'manual__2024-09-30T14:31:47.119862+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/tab_soccer_statics.py', '--cfg-path', '/tmp/tmpre8n_40_']
[2024-09-30T14:33:01.236+0000] {standard_task_runner.py:105} INFO - Job 181: Subtask fact_matches_statistics
[2024-09-30T14:33:01.268+0000] {task_command.py:467} INFO - Running <TaskInstance: tab_soccer_statics.fact_matches_statistics manual__2024-09-30T14:31:47.119862+00:00 [running]> on host 58fa97ed942d
[2024-09-30T14:33:01.331+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='daniel.cristancho' AIRFLOW_CTX_DAG_ID='tab_soccer_statics' AIRFLOW_CTX_TASK_ID='fact_matches_statistics' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T14:31:47.119862+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-30T14:31:47.119862+00:00'
[2024-09-30T14:33:01.331+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-30T14:33:03.266+0000] {fact_matches_statics.py:32} INFO - Start extract loaded data
[2024-09-30T14:33:03.267+0000] {fact_matches_statics.py:185} INFO - Staring data extraction for dim_teams
[2024-09-30T14:33:04.657+0000] {fact_matches_statics.py:189} INFO - 80 rows extracted from dim_teams
[2024-09-30T14:33:04.657+0000] {fact_matches_statics.py:190} INFO - Data extraction successfully finished
[2024-09-30T14:33:04.658+0000] {fact_matches_statics.py:185} INFO - Staring data extraction for fact_matches_statistics
[2024-09-30T14:33:04.934+0000] {fact_matches_statics.py:189} INFO - 30 rows extracted from fact_matches_statistics
[2024-09-30T14:33:04.934+0000] {fact_matches_statics.py:190} INFO - Data extraction successfully finished
[2024-09-30T14:33:04.936+0000] {fact_matches_statics.py:72} INFO - Request to match 1212917
[2024-09-30T14:33:04.936+0000] {fact_matches_statics.py:72} INFO - Request to match 1208559
[2024-09-30T14:33:04.936+0000] {fact_matches_statics.py:72} INFO - Request to match 1223646
[2024-09-30T14:33:04.939+0000] {fact_matches_statics.py:72} INFO - Request to match 1208557
[2024-09-30T14:33:04.940+0000] {fact_matches_statics.py:72} INFO - Request to match 1223650
[2024-09-30T14:33:04.940+0000] {fact_matches_statics.py:72} INFO - Request to match 1208076
[2024-09-30T14:33:04.941+0000] {fact_matches_statics.py:72} INFO - Request to match 1208077
[2024-09-30T14:33:04.941+0000] {fact_matches_statics.py:72} INFO - Request to match 1223653
[2024-09-30T14:33:04.942+0000] {fact_matches_statics.py:72} INFO - Request to match 1223647
[2024-09-30T14:33:04.943+0000] {fact_matches_statics.py:72} INFO - Request to match 1234262
[2024-09-30T14:33:04.944+0000] {fact_matches_statics.py:72} INFO - Request to match 1223652
[2024-09-30T14:33:04.944+0000] {fact_matches_statics.py:72} INFO - Request to match 1234259
[2024-09-30T14:33:04.944+0000] {fact_matches_statics.py:72} INFO - Request to match 1208075
[2024-09-30T14:33:04.945+0000] {fact_matches_statics.py:72} INFO - Request to match 1208079
[2024-09-30T14:33:04.945+0000] {fact_matches_statics.py:72} INFO - Request to match 1234260
[2024-09-30T14:33:04.945+0000] {fact_matches_statics.py:72} INFO - Request to match 1208565
[2024-09-30T14:33:04.946+0000] {fact_matches_statics.py:72} INFO - Request to match 1208564
[2024-09-30T14:33:04.946+0000] {fact_matches_statics.py:72} INFO - Request to match 1223654
[2024-09-30T14:33:04.947+0000] {fact_matches_statics.py:72} INFO - Request to match 1208080
[2024-09-30T14:33:04.947+0000] {fact_matches_statics.py:72} INFO - Request to match 1208073
[2024-09-30T14:33:05.371+0000] {fact_matches_statics.py:72} INFO - Request to match 1208072
[2024-09-30T14:33:05.378+0000] {fact_matches_statics.py:72} INFO - Request to match 1208561
[2024-09-30T14:33:05.378+0000] {fact_matches_statics.py:72} INFO - Request to match 1208560
[2024-09-30T14:33:05.384+0000] {fact_matches_statics.py:72} INFO - Request to match 1234254
[2024-09-30T14:33:05.384+0000] {fact_matches_statics.py:72} INFO - Request to match 1208078
[2024-09-30T14:33:05.385+0000] {fact_matches_statics.py:72} INFO - Request to match 1234261
[2024-09-30T14:33:05.386+0000] {fact_matches_statics.py:72} INFO - Request to match 1223648
[2024-09-30T14:33:05.388+0000] {fact_matches_statics.py:72} INFO - Request to match 1223645
[2024-09-30T14:33:05.391+0000] {fact_matches_statics.py:72} INFO - Request to match 1208074
[2024-09-30T14:33:05.391+0000] {fact_matches_statics.py:72} INFO - Request to match 1208562
[2024-09-30T14:33:05.834+0000] {logging_mixin.py:190} INFO - ****************** Unexpected error update fact matches statistics:  (<class 'UnboundLocalError'>, UnboundLocalError("cannot access local variable 'results_list' where it is not associated with a value"), <traceback object at 0x7299d7cd12c0>)
[2024-09-30T14:33:05.835+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tab_soccer_statics.py", line 83, in fact_matches_statistics
    pf.run()
  File "/opt/airflow/dags/src/soccer_statics/fact_matches_statics.py", line 49, in run
    results_list = pd.concat([results_list,result], ignore_index=True)
                              ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'results_list' where it is not associated with a value
[2024-09-30T14:33:05.843+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=tab_soccer_statics, task_id=fact_matches_statistics, run_id=manual__2024-09-30T14:31:47.119862+00:00, execution_date=20240930T143147, start_date=20240930T143301, end_date=20240930T143305
[2024-09-30T14:33:05.860+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-30T14:33:05.860+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 181 for task fact_matches_statistics (cannot access local variable 'results_list' where it is not associated with a value; 4345)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tab_soccer_statics.py", line 83, in fact_matches_statistics
    pf.run()
  File "/opt/airflow/dags/src/soccer_statics/fact_matches_statics.py", line 49, in run
    results_list = pd.concat([results_list,result], ignore_index=True)
                              ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'results_list' where it is not associated with a value
[2024-09-30T14:33:05.898+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-30T14:33:05.911+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-30T14:33:05.913+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
