[2024-10-08T01:50:28.076+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-08T01:50:28.091+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tab_soccer_statics.dim_teams manual__2024-10-08T01:50:20.566545+00:00 [queued]>
[2024-10-08T01:50:28.097+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tab_soccer_statics.dim_teams manual__2024-10-08T01:50:20.566545+00:00 [queued]>
[2024-10-08T01:50:28.097+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-08T01:50:28.108+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): dim_teams> on 2024-10-08 01:50:20.566545+00:00
[2024-10-08T01:50:28.119+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=491) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-08T01:50:28.121+0000] {standard_task_runner.py:72} INFO - Started process 516 to run task
[2024-10-08T01:50:28.122+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tab_soccer_statics', 'dim_teams', 'manual__2024-10-08T01:50:20.566545+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/tab_soccer_statics.py', '--cfg-path', '/tmp/tmpt5xu14c6']
[2024-10-08T01:50:28.124+0000] {standard_task_runner.py:105} INFO - Job 100: Subtask dim_teams
[2024-10-08T01:50:28.164+0000] {task_command.py:467} INFO - Running <TaskInstance: tab_soccer_statics.dim_teams manual__2024-10-08T01:50:20.566545+00:00 [running]> on host f74ce347067d
[2024-10-08T01:50:28.246+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='daniel.cristancho' AIRFLOW_CTX_DAG_ID='tab_soccer_statics' AIRFLOW_CTX_TASK_ID='dim_teams' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T01:50:20.566545+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T01:50:20.566545+00:00'
[2024-10-08T01:50:28.247+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-08T01:50:28.300+0000] {warnings.py:112} WARNING - /opt/***/dags/tab_soccer_statics.py:35: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  data_extract = pd.read_json(data_extract)

[2024-10-08T01:50:30.130+0000] {dim_teams.py:35} INFO - Start extract loaded data
[2024-10-08T01:50:30.131+0000] {dim_teams.py:171} INFO - Staring data extraction for dim_teams
[2024-10-08T01:50:36.642+0000] {dim_teams.py:175} INFO - 244 rows extracted from dim_teams
[2024-10-08T01:50:36.642+0000] {dim_teams.py:176} INFO - Data extraction successfully finished
[2024-10-08T01:50:36.642+0000] {dim_teams.py:40} INFO - Start transform data
[2024-10-08T01:51:11.778+0000] {warnings.py:112} WARNING - /opt/***/dags/src/soccer_statics/dim_teams.py:115: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_append["uuid"] = result_append.apply(lambda _: uuid.uuid4(), axis=1)

[2024-10-08T01:51:11.784+0000] {warnings.py:112} WARNING - /opt/***/dags/src/soccer_statics/dim_teams.py:116: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_append["created_at"] = pd.to_datetime(

[2024-10-08T01:51:11.785+0000] {warnings.py:112} WARNING - /opt/***/dags/src/soccer_statics/dim_teams.py:119: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_append["updated_at"] = pd.to_datetime(

[2024-10-08T01:51:11.786+0000] {warnings.py:112} WARNING - /opt/***/dags/src/soccer_statics/dim_teams.py:122: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_append["id_team"] = result_append["id_team"].astype("Int64")

[2024-10-08T01:51:11.792+0000] {dim_teams.py:43} INFO - Start load new data
[2024-10-08T01:51:11.792+0000] {dim_teams.py:156} INFO - writing dim_teams table
[2024-10-08T01:51:14.674+0000] {dim_teams.py:160} INFO - 11 rows load in dim_teams
[2024-10-08T01:51:14.674+0000] {dim_teams.py:161} INFO - loading operation finished successfully for dim_teams
[2024-10-08T01:51:14.675+0000] {dim_teams.py:53} INFO - Start update old data
[2024-10-08T01:51:18.273+0000] {dim_teams.py:66} INFO - The update of 69 rows was made.
[2024-10-08T01:51:18.383+0000] {logging_mixin.py:190} INFO - ****************** Success process update dim teams
[2024-10-08T01:51:18.386+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-08T01:51:18.396+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-08T01:51:18.397+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=tab_soccer_statics, task_id=dim_teams, run_id=manual__2024-10-08T01:50:20.566545+00:00, execution_date=20241008T015020, start_date=20241008T015028, end_date=20241008T015118
[2024-10-08T01:51:18.448+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-08T01:51:18.466+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-08T01:51:18.467+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
